### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by krt16s** [MajeurAndroid/Applications-Info#1]
Could you provide some details for building this app from source? It looks like it's not a standard ant+sdk build? Also note:.

* You should not use jar files as depdencies, especially if the source code is hosted on googlecode which will vanish some day. I'd recommend import the XmlApkParser files directly into the project.

* The AndroidManifest.xml should have android:versioncode and android:versionname set.

**Comment by MajeurAndroid** [comment]
Jar isn't used anymore, if you take a look at java code, you'll see that xmlapkparser code is used instead.
It's the default source code, you have to import it in your IDE.
For versionName and versionCode I'll fix this. Personally I use graddle so these values are provided in build.graddle file. I'll move them to manifest file.

**Comment by krt16s** [comment]
Or just publish the gradle files and the root project? Minus the signing info that is.

**Comment by krt16s** [comment]
Thanks for the quick response. Everything works fine now.
