### ISSUE TITLE
Certificate info

### ISSUE THREAD

**Issue by KOLANICH** [MajeurAndroid/Applications-Info#4]
Hello, could you add displaying of info about cert like in [Checkey](https://github.com/guardianproject/checkey)?

**Comment by MajeurAndroid** [comment]
You can already access signature of each app under Signature tab (You can copy paste). More specific features about signature aren't planed.

**Comment by dalb8** [comment]
Checkey gives the name/company/address info. For people who build apps themselves it's useful to know whether the version they have installed was signed by the developer or not.
