### ISSUE TITLE
Security analysis

### ISSUE THREAD

**Issue by KOLANICH** [MajeurAndroid/Applications-Info#6]
Could you add security analysis feature?
I mean
1 group the apps with the same public key (for example, the f-droid one) and show warnings if large amount of apps have the same pk
2 show warnings about the apps whoose signature is weak due either weak hash function (for example, md5 or sha1) or weak trapdoor function (for example rsa-1024)
3 heuristically detect overpermissioned apps
4 check packages on virustotal

**Comment by MajeurAndroid** [comment]
This is not the purpose of the app, sorry.
